## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - julia: nightly
dist: xenial
env:
  - JULIA_CMDSTAN_HOME="$HOME/cmdstan-2.19.1/"
before_install:
  - OLDWD=`pwd`
  - cd ~
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.19.1/cmdstan-2.19.1.tar.gz
  - tar -xzpf cmdstan-2.19.1.tar.gz
  - make -C $JULIA_CMDSTAN_HOME build
  - cd $OLDWD
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("DiffEqBayes")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("DiffEqBayes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
